[package]
name = "nop-json"
version = "0.0.1"
authors = ["Jeremiah Shaulov <jeremiah.shaulov@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "JSON serialization/deserialization (full-featured, modern, optimal, streaming, direct into struct)"
repository = "https://github.com/jeremiah-shaulov/nop-json"
keywords = ["json"]

[dependencies]
numtoa = "*"
nop-json-derive = {git = "https://github.com/jeremiah-shaulov/nop-json-derive"}
